name: stream_feed_flutter_core
description: Stream Feed official Flutter SDK Core. Build your own feed experience using Dart and Flutter.
version: 0.8.0
repository: https://github.com/GetStream/stream-feed-flutter
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues
homepage: https://getstream.io/
environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"
publish_to: none

dependencies:
  dio: ^5.4.3+1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  meta: ^1.7.0
  rxdart: ^0.28.0
#  stream_feed: ^0.6.0+2
  stream_feed:
    path: ../stream_feed

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
#  stream_feed:
#    git:
#      url: https://github.com/toaingo2108/stream-feed-flutter
#      path: packages/stream_feed
